/**
 * Tests for the score engine.
 *
 * Ground truth sources:
 * - parity fixture: src/lib/score/__fixtures__/parity.json, generated by
 *   pipeline/reference/generate_fixture.py via compute_reference.py.
 * - weights: robotability-nyc/survey_processing/feature_weights.csv
 * - polarities: robotability-nyc/feature_processing/score.ipynb cell 96.
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import { computeScore, ScoreInputError } from './engine.ts';
import type { FeatureStats } from './engine.ts';
import { FEATURES, WEIGHTS } from './weights.ts';
import type { Feature } from './weights.ts';
import { POLARITIES } from './polarities.ts';

type ParityRow = {
  values: Record<Feature, number>;
  stats: Record<Feature, FeatureStats>;
  expected: number;
};

const PARITY_TOLERANCE = 0.001;

// Closed form for all-degenerate stats. Every normalized value is 0.5,
// so score = 0.5 x sum(polarity x weight). Computed independently with
// the Python reference from the full-precision weights.
const DEGENERATE_CLOSED_FORM = 0.0951214567508061;

function loadParityRows(): ParityRow[] {
  const path = fileURLToPath(new URL('./__fixtures__/parity.json', import.meta.url));
  return JSON.parse(readFileSync(path, 'utf8')) as ParityRow[];
}

function loadWeightsCsv(): Record<string, number> {
  const path = fileURLToPath(
    new URL(
      '../../../robotability-nyc/survey_processing/feature_weights.csv',
      import.meta.url,
    ),
  );
  const lines = readFileSync(path, 'utf8').trim().split(/\r?\n/);
  expect(lines[0]).toBe('Feature,Weight');
  const parsed: Record<string, number> = {};
  for (const line of lines.slice(1)) {
    const [name, weight] = line.split(',');
    parsed[name] = Number.parseFloat(weight);
  }
  return parsed;
}

function fillValues(fill: number): Record<Feature, number> {
  const values = {} as Record<Feature, number>;
  for (const feature of FEATURES) {
    values[feature] = fill;
  }
  return values;
}

function unitStats(): Record<Feature, FeatureStats> {
  const stats = {} as Record<Feature, FeatureStats>;
  for (const feature of FEATURES) {
    stats[feature] = { min: 0, max: 1 };
  }
  return stats;
}

describe('parity with the Python reference', () => {
  const rows = loadParityRows();

  it('fixture has exactly 100 rows', () => {
    expect(rows).toHaveLength(100);
  });

  it('every row matches computeScore within 0.001 and reports the max error', () => {
    let maxError = 0;
    rows.forEach((row, index) => {
      const actual = computeScore(row.values, row.stats);
      const error = Math.abs(actual - row.expected);
      if (error > maxError) {
        maxError = error;
      }
      // Numeric assertion per row. A wrong formula fails here with the
      // row index and both numbers in the diff.
      expect(error, `fixture row ${index} diverges`).toBeLessThan(PARITY_TOLERANCE);
    });
    // Report the observed max absolute error in the test output.
    console.info(`max parity error across ${rows.length} rows: ${maxError}`);
    expect(maxError).toBeLessThan(PARITY_TOLERANCE);
  });
});

describe('weights', () => {
  it('WEIGHTS deep-equals feature_weights.csv', () => {
    const csv = loadWeightsCsv();
    expect(Object.keys(csv).sort()).toEqual([...FEATURES].sort());
    expect(Object.keys(WEIGHTS)).toHaveLength(19);
    for (const feature of FEATURES) {
      // Exact double equality. Both sides parse the same decimal text.
      expect(WEIGHTS[feature], `weight for ${feature}`).toBe(csv[feature]);
    }
  });
});

describe('polarities', () => {
  it('POLARITIES deep-equals the map from score.ipynb cell 96', () => {
    expect(POLARITIES).toEqual({
      sidewalk_width: 1,
      pedestrian_density: -1,
      street_furniture_density: -1,
      sidewalk_roughness: -1,
      surface_condition: 1,
      communication_infrastructure: 1,
      slope_gradient: -1,
      charging_station_proximity: 1,
      curb_ramp_availability: 1,
      crowd_dynamics: 1,
      traffic_management: 1,
      surveillance_coverage: 1,
      zoning_laws: 1,
      bike_lane_availability: 1,
      gps_signal_strength: 1,
      bicycle_traffic: -1,
      vehicle_traffic: -1,
      digital_map_existence: 1,
      intersection_safety: -1,
    });
  });
});

describe('malformed input', () => {
  it('throws and names the feature when a value key is missing', () => {
    const values = fillValues(0);
    delete (values as Partial<Record<Feature, number>>).pedestrian_density;
    expect(() => computeScore(values, unitStats())).toThrow(/pedestrian_density/);
  });

  it('throws a ScoreInputError when a value key is missing', () => {
    const values = fillValues(0);
    delete (values as Partial<Record<Feature, number>>).sidewalk_width;
    try {
      computeScore(values, unitStats());
      expect.unreachable('computeScore must throw for a missing value key');
    } catch (error) {
      expect(error).toBeInstanceOf(ScoreInputError);
      expect((error as Error).name).toBe('ScoreInputError');
      expect((error as Error).message).toContain('sidewalk_width');
    }
  });

  it('throws and names the feature when a stats key is missing', () => {
    const stats = unitStats();
    delete (stats as Partial<Record<Feature, FeatureStats>>).intersection_safety;
    expect(() => computeScore(fillValues(0), stats)).toThrow(/intersection_safety/);
  });
});

describe('degenerate stats (max === min)', () => {
  it('uses the 0.5 midpoint and matches the closed form', () => {
    // All stats windows are degenerate. Every normalized value must be
    // 0.5, so the score is 0.5 x sum(polarity x weight), independent of
    // the raw values.
    const stats = {} as Record<Feature, FeatureStats>;
    for (const feature of FEATURES) {
      stats[feature] = { min: 3, max: 3 };
    }
    const actual = computeScore(fillValues(7), stats);
    expect(Math.abs(actual - DEGENERATE_CLOSED_FORM)).toBeLessThan(1e-12);
  });

  it('closed form equals 0.5 x (positive weight sum - negative weight sum)', () => {
    let signedWeightSum = 0;
    for (const feature of FEATURES) {
      signedWeightSum += POLARITIES[feature] * WEIGHTS[feature];
    }
    expect(Math.abs(0.5 * signedWeightSum - DEGENERATE_CLOSED_FORM)).toBeLessThan(1e-12);
  });
});
